/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as SocialRouteImport } from './routes/social'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as Sheet3RouteImport } from './routes/sheet3'
import { Route as Sheet2RouteImport } from './routes/sheet2'
import { Route as Sheet1RouteImport } from './routes/sheet1'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PalgridRouteImport } from './routes/palgrid'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthcontextRouteImport } from './routes/authcontext'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const LibraryLazyRouteImport = createFileRoute('/library')()
const FiguresLazyRouteImport = createFileRoute('/figures')()
const CalendarLazyRouteImport = createFileRoute('/calendar')()

const LibraryLazyRoute = LibraryLazyRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/library.lazy').then((d) => d.Route))
const FiguresLazyRoute = FiguresLazyRouteImport.update({
  id: '/figures',
  path: '/figures',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/figures.lazy').then((d) => d.Route))
const CalendarLazyRoute = CalendarLazyRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/calendar.lazy').then((d) => d.Route))
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const Sheet3Route = Sheet3RouteImport.update({
  id: '/sheet3',
  path: '/sheet3',
  getParentRoute: () => rootRouteImport,
} as any)
const Sheet2Route = Sheet2RouteImport.update({
  id: '/sheet2',
  path: '/sheet2',
  getParentRoute: () => rootRouteImport,
} as any)
const Sheet1Route = Sheet1RouteImport.update({
  id: '/sheet1',
  path: '/sheet1',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PalgridRoute = PalgridRouteImport.update({
  id: '/palgrid',
  path: '/palgrid',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthcontextRoute = AuthcontextRouteImport.update({
  id: '/authcontext',
  path: '/authcontext',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/authcontext': typeof AuthcontextRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/home': typeof HomeRoute
  '/messages': typeof MessagesRoute
  '/palgrid': typeof PalgridRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/sheet1': typeof Sheet1Route
  '/sheet2': typeof Sheet2Route
  '/sheet3': typeof Sheet3Route
  '/signup': typeof SignupRoute
  '/social': typeof SocialRoute
  '/timeline': typeof TimelineRoute
  '/calendar': typeof CalendarLazyRoute
  '/figures': typeof FiguresLazyRoute
  '/library': typeof LibraryLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/authcontext': typeof AuthcontextRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/home': typeof HomeRoute
  '/messages': typeof MessagesRoute
  '/palgrid': typeof PalgridRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/sheet1': typeof Sheet1Route
  '/sheet2': typeof Sheet2Route
  '/sheet3': typeof Sheet3Route
  '/signup': typeof SignupRoute
  '/social': typeof SocialRoute
  '/timeline': typeof TimelineRoute
  '/calendar': typeof CalendarLazyRoute
  '/figures': typeof FiguresLazyRoute
  '/library': typeof LibraryLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/authcontext': typeof AuthcontextRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/home': typeof HomeRoute
  '/messages': typeof MessagesRoute
  '/palgrid': typeof PalgridRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/sheet1': typeof Sheet1Route
  '/sheet2': typeof Sheet2Route
  '/sheet3': typeof Sheet3Route
  '/signup': typeof SignupRoute
  '/social': typeof SocialRoute
  '/timeline': typeof TimelineRoute
  '/calendar': typeof CalendarLazyRoute
  '/figures': typeof FiguresLazyRoute
  '/library': typeof LibraryLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/authcontext'
    | '/contact'
    | '/donate'
    | '/home'
    | '/messages'
    | '/palgrid'
    | '/privacy'
    | '/settings'
    | '/sheet1'
    | '/sheet2'
    | '/sheet3'
    | '/signup'
    | '/social'
    | '/timeline'
    | '/calendar'
    | '/figures'
    | '/library'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/authcontext'
    | '/contact'
    | '/donate'
    | '/home'
    | '/messages'
    | '/palgrid'
    | '/privacy'
    | '/settings'
    | '/sheet1'
    | '/sheet2'
    | '/sheet3'
    | '/signup'
    | '/social'
    | '/timeline'
    | '/calendar'
    | '/figures'
    | '/library'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/authcontext'
    | '/contact'
    | '/donate'
    | '/home'
    | '/messages'
    | '/palgrid'
    | '/privacy'
    | '/settings'
    | '/sheet1'
    | '/sheet2'
    | '/sheet3'
    | '/signup'
    | '/social'
    | '/timeline'
    | '/calendar'
    | '/figures'
    | '/library'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthcontextRoute: typeof AuthcontextRoute
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  HomeRoute: typeof HomeRoute
  MessagesRoute: typeof MessagesRoute
  PalgridRoute: typeof PalgridRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  Sheet1Route: typeof Sheet1Route
  Sheet2Route: typeof Sheet2Route
  Sheet3Route: typeof Sheet3Route
  SignupRoute: typeof SignupRoute
  SocialRoute: typeof SocialRoute
  TimelineRoute: typeof TimelineRoute
  CalendarLazyRoute: typeof CalendarLazyRoute
  FiguresLazyRoute: typeof FiguresLazyRoute
  LibraryLazyRoute: typeof LibraryLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/figures': {
      id: '/figures'
      path: '/figures'
      fullPath: '/figures'
      preLoaderRoute: typeof FiguresLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sheet3': {
      id: '/sheet3'
      path: '/sheet3'
      fullPath: '/sheet3'
      preLoaderRoute: typeof Sheet3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sheet2': {
      id: '/sheet2'
      path: '/sheet2'
      fullPath: '/sheet2'
      preLoaderRoute: typeof Sheet2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sheet1': {
      id: '/sheet1'
      path: '/sheet1'
      fullPath: '/sheet1'
      preLoaderRoute: typeof Sheet1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/palgrid': {
      id: '/palgrid'
      path: '/palgrid'
      fullPath: '/palgrid'
      preLoaderRoute: typeof PalgridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authcontext': {
      id: '/authcontext'
      path: '/authcontext'
      fullPath: '/authcontext'
      preLoaderRoute: typeof AuthcontextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthcontextRoute: AuthcontextRoute,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  HomeRoute: HomeRoute,
  MessagesRoute: MessagesRoute,
  PalgridRoute: PalgridRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  Sheet1Route: Sheet1Route,
  Sheet2Route: Sheet2Route,
  Sheet3Route: Sheet3Route,
  SignupRoute: SignupRoute,
  SocialRoute: SocialRoute,
  TimelineRoute: TimelineRoute,
  CalendarLazyRoute: CalendarLazyRoute,
  FiguresLazyRoute: FiguresLazyRoute,
  LibraryLazyRoute: LibraryLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
